# This file was @generated by cargo2nix 0.12.0.
# It is not intended to be manually edited.

args@{
  release ? true,
  rootFeatures ? [
    "heapless/default"
  ],
  rustPackages,
  buildRustPackages,
  hostPlatform,
  hostPlatformCpu ? null,
  hostPlatformFeatures ? [],
  target ? null,
  codegenOpts ? null,
  profileOpts ? null,
  cargoUnstableFlags ? null,
  rustcLinkFlags ? null,
  rustcBuildFlags ? null,
  mkRustCrate,
  rustLib,
  lib,
  workspaceSrc,
  ignoreLockHash,
  cargoConfig ? {},
}:
let
  nixifiedLockHash = "4b2f745cbd7b064d811d31f1c275b8f8e284ca1ff7f66ad23976089df17acf65";
  workspaceSrc = if args.workspaceSrc == null then ./. else args.workspaceSrc;
  currentLockHash = builtins.hashFile "sha256" (workspaceSrc + /Cargo.lock);
  lockHashIgnored = if ignoreLockHash
                  then builtins.trace "Ignoring lock hash" ignoreLockHash
                  else ignoreLockHash;
in if !lockHashIgnored && (nixifiedLockHash != currentLockHash) then
  throw ("Cargo.nix ${nixifiedLockHash} is out of sync with Cargo.lock ${currentLockHash}")
else let
  inherit (rustLib) fetchCratesIo fetchCrateLocal fetchCrateGit fetchCrateAlternativeRegistry expandFeatures decideProfile genDrvsByProfile;
  cargoConfig' = if cargoConfig != {} then cargoConfig else
                 if builtins.pathExists ./.cargo/config then lib.importTOML ./.cargo/config else
                 if builtins.pathExists ./.cargo/config.toml then lib.importTOML ./.cargo/config.toml else {};
  profilesByName = {
  };
  rootFeatures' = expandFeatures rootFeatures;
  overridableMkRustCrate = f:
    let
      drvs = genDrvsByProfile profilesByName ({ profile, profileName }: mkRustCrate ({
        inherit release profile hostPlatformCpu hostPlatformFeatures target profileOpts codegenOpts cargoUnstableFlags rustcLinkFlags rustcBuildFlags; 
        cargoConfig = cargoConfig';
      } // (f profileName)));
    in { compileMode ? null, profileName ? decideProfile compileMode release }:
      let drv = drvs.${profileName}; in if compileMode == null then drv else drv.override { inherit compileMode; };
in
{
  cargo2nixVersion = "0.12.0";
  workspace = {
    heapless = rustPackages.unknown.heapless."0.9.2";
  };
  "registry+https://github.com/rust-lang/crates.io-index".bitflags."1.3.2" = overridableMkRustCrate (profileName: rec {
    name = "bitflags";
    version = "1.3.2";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "bef38d45163c2f1dde094a7dfd33ccf595c92905c8f8f4fdc18d06fb1037718a"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/defmt") "default")
    ];
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".byteorder."1.5.0" = overridableMkRustCrate (profileName: rec {
    name = "byteorder";
    version = "1.5.0";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "1fd0f2584146f6f2ef48085050886acf353beff7305ebd1ae69500e27c67f64b"; };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".bytes."1.10.1" = overridableMkRustCrate (profileName: rec {
    name = "bytes";
    version = "1.10.1";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "d71b6127be86fdcfddb610f7182ac57211d4b18a3e9c82eb2d17662f2227ad6a"; };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".critical-section."1.2.0" = overridableMkRustCrate (profileName: rec {
    name = "critical-section";
    version = "1.2.0";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "790eea4361631c5e7d22598ecd5723ff611904e3344ce8720784c93e3d83d40b"; };
    features = builtins.concatLists [
      [ "restore-state-bool" ]
      [ "std" ]
    ];
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".defmt."1.0.1" = overridableMkRustCrate (profileName: rec {
    name = "defmt";
    version = "1.0.1";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "548d977b6da32fa1d1fda2876453da1e7df63ad0304c8b3dae4dbe7b96f39b78"; };
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" then "bitflags" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".bitflags."1.3.2" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "defmt_macros" else null } = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".defmt-macros."1.0.1" { profileName = "__noProfile"; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".defmt-macros."1.0.1" = overridableMkRustCrate (profileName: rec {
    name = "defmt-macros";
    version = "1.0.1";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "3d4fc12a85bcf441cfe44344c4b72d58493178ce635338a3f3b78943aceb258e"; };
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" then "defmt_parser" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".defmt-parser."1.0.0" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "proc_macro_error2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro-error2."2.0.1" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "syn" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".syn."2.0.110" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".defmt-parser."1.0.0" = overridableMkRustCrate (profileName: rec {
    name = "defmt-parser";
    version = "1.0.0";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "10d60334b3b2e7c9d91ef8150abfb6fa4c1c39ebbcf4a81c2e346aad939fee3e"; };
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" then "thiserror" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".thiserror."2.0.17" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".embedded-io."0.7.1" = overridableMkRustCrate (profileName: rec {
    name = "embedded-io";
    version = "0.7.1";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "9eb1aa714776b75c7e67e1da744b81a129b3ff919c8712b5e1b32252c1f07cc7"; };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".hash32."0.3.1" = overridableMkRustCrate (profileName: rec {
    name = "hash32";
    version = "0.3.1";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "47d60b12902ba28e2730cd37e95b8c9223af2808df9e902d4df49588d1470606"; };
    dependencies = {
      byteorder = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".byteorder."1.5.0" { inherit profileName; }).out;
    };
  });
  
  "unknown".heapless."0.9.2" = overridableMkRustCrate (profileName: rec {
    name = "heapless";
    version = "0.9.2";
    registry = "unknown";
    src = fetchCrateLocal workspaceSrc;
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/alloc") "alloc")
      (lib.optional (rootFeatures' ? "heapless/bytes") "bytes")
      (lib.optional (rootFeatures' ? "heapless/defmt") "defmt")
      (lib.optional (rootFeatures' ? "heapless/embedded-io-v0.7") "embedded-io-v0.7")
      (lib.optional (rootFeatures' ? "heapless/mpmc_large") "mpmc_large")
      (lib.optional (rootFeatures' ? "heapless/nightly") "nightly")
      (lib.optional (rootFeatures' ? "heapless/portable-atomic" || rootFeatures' ? "heapless/portable-atomic-critical-section" || rootFeatures' ? "heapless/portable-atomic-unsafe-assume-single-core") "portable-atomic")
      (lib.optional (rootFeatures' ? "heapless/portable-atomic-critical-section") "portable-atomic-critical-section")
      (lib.optional (rootFeatures' ? "heapless/portable-atomic-unsafe-assume-single-core") "portable-atomic-unsafe-assume-single-core")
      (lib.optional (rootFeatures' ? "heapless/serde") "serde")
      (lib.optional (rootFeatures' ? "heapless/ufmt") "ufmt")
      (lib.optional (rootFeatures' ? "heapless/zeroize") "zeroize")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/bytes" then "bytes" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".bytes."1.10.1" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "defmt" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".defmt."1.0.1" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/embedded-io-v0.7" then "embedded_io" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".embedded-io."0.7.1" { inherit profileName; }).out;
      hash32 = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".hash32."0.3.1" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/portable-atomic" || rootFeatures' ? "heapless/portable-atomic-critical-section" || rootFeatures' ? "heapless/portable-atomic-unsafe-assume-single-core" then "portable_atomic" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".portable-atomic."1.11.1" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/serde" then "serde_core" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".serde_core."1.0.228" { inherit profileName; }).out;
      ${ if hostPlatform.parsed.cpu.name == "armv6l" || hostPlatform.parsed.cpu.name == "armv7l" || hostPlatform.parsed.cpu.bits == 32 || hostPlatform.parsed.cpu.bits == 64 then "stable_deref_trait" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".stable_deref_trait."1.2.1" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/ufmt" then "ufmt" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".ufmt."0.2.0" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/ufmt" then "ufmt_write" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".ufmt-write."0.1.0" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/zeroize" then "zeroize" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".zeroize."1.8.2" { inherit profileName; }).out;
    };
    devDependencies = {
      critical_section = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".critical-section."1.2.0" { inherit profileName; }).out;
      static_assertions = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".static_assertions."1.1.0" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".portable-atomic."1.11.1" = overridableMkRustCrate (profileName: rec {
    name = "portable-atomic";
    version = "1.11.1";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "f84267b20a16ea918e43c6a88433c2d54fa145c92a811b5b047ccbe153674483"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/portable-atomic-critical-section") "critical-section")
      (lib.optional (rootFeatures' ? "heapless/portable-atomic" || rootFeatures' ? "heapless/portable-atomic-critical-section" || rootFeatures' ? "heapless/portable-atomic-unsafe-assume-single-core") "default")
      (lib.optional (rootFeatures' ? "heapless/portable-atomic" || rootFeatures' ? "heapless/portable-atomic-critical-section" || rootFeatures' ? "heapless/portable-atomic-unsafe-assume-single-core") "fallback")
      (lib.optional (rootFeatures' ? "heapless/portable-atomic-unsafe-assume-single-core") "unsafe-assume-single-core")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/portable-atomic-critical-section" then "critical_section" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".critical-section."1.2.0" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".proc-macro-error-attr2."2.0.0" = overridableMkRustCrate (profileName: rec {
    name = "proc-macro-error-attr2";
    version = "2.0.0";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "96de42df36bb9bba5542fe9f1a054b8cc87e172759a1868aa05c1f3acc89dfc5"; };
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".proc-macro-error2."2.0.1" = overridableMkRustCrate (profileName: rec {
    name = "proc-macro-error2";
    version = "2.0.1";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "11ec05c52be0a07b08061f7dd003e7d7092e0472bc731b4af7bb1ef876109802"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/defmt") "default")
      (lib.optional (rootFeatures' ? "heapless/defmt") "syn-error")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" then "proc_macro_error_attr2" else null } = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro-error-attr2."2.0.0" { profileName = "__noProfile"; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "syn" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".syn."2.0.110" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" = overridableMkRustCrate (profileName: rec {
    name = "proc-macro2";
    version = "1.0.103";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "5ee95bc4ef87b8d5ba32e8b7714ccc834865276eab0aed5c9958d00ec45f49e8"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/ufmt" || rootFeatures' ? "heapless/zeroize") "default")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/ufmt" || rootFeatures' ? "heapless/zeroize") "proc-macro")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/ufmt" || rootFeatures' ? "heapless/zeroize" then "unicode_ident" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".unicode-ident."1.0.22" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" = overridableMkRustCrate (profileName: rec {
    name = "quote";
    version = "1.0.42";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "a338cc41d27e6cc6dce6cefc13a0729dfbb81c262b1f519331575dd80ef3067f"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/ufmt" || rootFeatures' ? "heapless/zeroize") "default")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/ufmt" || rootFeatures' ? "heapless/zeroize") "proc-macro")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/ufmt" || rootFeatures' ? "heapless/zeroize" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".serde_core."1.0.228" = overridableMkRustCrate (profileName: rec {
    name = "serde_core";
    version = "1.0.228";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "41d385c7d4ca58e59fc732af25c3983b67ac852c1a25000afe1175de458b67ad"; };
    dependencies = {
      ${ if false then "serde_derive" else null } = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".serde_derive."1.0.228" { profileName = "__noProfile"; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".serde_derive."1.0.228" = overridableMkRustCrate (profileName: rec {
    name = "serde_derive";
    version = "1.0.228";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "d540f220d3187173da220f885ab66608367b6574e925011a9353e4badda91d79"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/serde") "default")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/serde" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/serde" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/serde" then "syn" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".syn."2.0.110" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".stable_deref_trait."1.2.1" = overridableMkRustCrate (profileName: rec {
    name = "stable_deref_trait";
    version = "1.2.1";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "6ce2be8dc25455e1f91df71bfa12ad37d7af1092ae736f3a6cd0e37bc7810596"; };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".static_assertions."1.1.0" = overridableMkRustCrate (profileName: rec {
    name = "static_assertions";
    version = "1.1.0";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "a2eb9349b6444b326872e140eb1cf5e7c522154d69e7a0ffb0fb81c06b37543f"; };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".syn."1.0.109" = overridableMkRustCrate (profileName: rec {
    name = "syn";
    version = "1.0.109";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "72b64191b275b66ffe2469e8af2c1cfe3bafa67b529ead792a6d0160888b4237"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/ufmt") "clone-impls")
      (lib.optional (rootFeatures' ? "heapless/ufmt") "default")
      (lib.optional (rootFeatures' ? "heapless/ufmt") "derive")
      (lib.optional (rootFeatures' ? "heapless/ufmt") "full")
      (lib.optional (rootFeatures' ? "heapless/ufmt") "parsing")
      (lib.optional (rootFeatures' ? "heapless/ufmt") "printing")
      (lib.optional (rootFeatures' ? "heapless/ufmt") "proc-macro")
      (lib.optional (rootFeatures' ? "heapless/ufmt") "quote")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/ufmt" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/ufmt" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/ufmt" then "unicode_ident" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".unicode-ident."1.0.22" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".syn."2.0.110" = overridableMkRustCrate (profileName: rec {
    name = "syn";
    version = "2.0.110";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "a99801b5bd34ede4cf3fc688c5919368fea4e4814a4664359503e6015b280aea"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/zeroize") "clone-impls")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/zeroize") "default")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/zeroize") "derive")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/zeroize") "extra-traits")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/zeroize") "full")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/zeroize") "parsing")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/zeroize") "printing")
      (lib.optional (rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/zeroize") "proc-macro")
      (lib.optional (rootFeatures' ? "heapless/zeroize") "visit")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/zeroize" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/zeroize" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" || rootFeatures' ? "heapless/serde" || rootFeatures' ? "heapless/zeroize" then "unicode_ident" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".unicode-ident."1.0.22" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".thiserror."2.0.17" = overridableMkRustCrate (profileName: rec {
    name = "thiserror";
    version = "2.0.17";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "f63587ca0f12b72a0600bcba1d40081f830876000bb46dd2337a3051618f4fc8"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/defmt") "default")
      (lib.optional (rootFeatures' ? "heapless/defmt") "std")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" then "thiserror_impl" else null } = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".thiserror-impl."2.0.17" { profileName = "__noProfile"; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".thiserror-impl."2.0.17" = overridableMkRustCrate (profileName: rec {
    name = "thiserror-impl";
    version = "2.0.17";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "3ff15c8ecd7de3849db632e14d18d2571fa09dfc5ed93479bc4485c7a517c913"; };
    dependencies = {
      ${ if rootFeatures' ? "heapless/defmt" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/defmt" then "syn" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".syn."2.0.110" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".ufmt."0.2.0" = overridableMkRustCrate (profileName: rec {
    name = "ufmt";
    version = "0.2.0";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "1a64846ec02b57e9108d6469d98d1648782ad6bb150a95a9baac26900bbeab9d"; };
    dependencies = {
      ${ if rootFeatures' ? "heapless/ufmt" then "ufmt_macros" else null } = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".ufmt-macros."0.3.0" { profileName = "__noProfile"; }).out;
      ${ if rootFeatures' ? "heapless/ufmt" then "ufmt_write" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".ufmt-write."0.1.0" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".ufmt-macros."0.3.0" = overridableMkRustCrate (profileName: rec {
    name = "ufmt-macros";
    version = "0.3.0";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "d337d3be617449165cb4633c8dece429afd83f84051024079f97ad32a9663716"; };
    dependencies = {
      ${ if rootFeatures' ? "heapless/ufmt" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/ufmt" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/ufmt" then "syn" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".syn."1.0.109" { inherit profileName; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".ufmt-write."0.1.0" = overridableMkRustCrate (profileName: rec {
    name = "ufmt-write";
    version = "0.1.0";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "e87a2ed6b42ec5e28cc3b94c09982969e9227600b2e3dcbc1db927a84c06bd69"; };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".unicode-ident."1.0.22" = overridableMkRustCrate (profileName: rec {
    name = "unicode-ident";
    version = "1.0.22";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "9312f7c4f6ff9069b165498234ce8be658059c6728633667c526e27dc2cf1df5"; };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".zeroize."1.8.2" = overridableMkRustCrate (profileName: rec {
    name = "zeroize";
    version = "1.8.2";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "b97154e67e32c85465826e8bcc1c59429aaaf107c1e4a9e53c8d8ccd5eff88d0"; };
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "heapless/zeroize") "derive")
      (lib.optional (rootFeatures' ? "heapless/zeroize") "zeroize_derive")
    ];
    dependencies = {
      ${ if rootFeatures' ? "heapless/zeroize" then "zeroize_derive" else null } = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".zeroize_derive."1.4.2" { profileName = "__noProfile"; }).out;
    };
  });
  
  "registry+https://github.com/rust-lang/crates.io-index".zeroize_derive."1.4.2" = overridableMkRustCrate (profileName: rec {
    name = "zeroize_derive";
    version = "1.4.2";
    registry = "registry+https://github.com/rust-lang/crates.io-index";
    src = fetchCratesIo { inherit name version; sha256 = "ce36e65b0d2999d2aafac989fb249189a141aee1f53c612c1f37d72631959f69"; };
    dependencies = {
      ${ if rootFeatures' ? "heapless/zeroize" then "proc_macro2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.103" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/zeroize" then "quote" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.42" { inherit profileName; }).out;
      ${ if rootFeatures' ? "heapless/zeroize" then "syn" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".syn."2.0.110" { inherit profileName; }).out;
    };
  });
  
}
